server:
  port: ${PORT}
finsys:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}
  interest-rate:
    monthly: ${MONTHLY_INTEREST_RATE}
  viacep:
    url: ${VIA_CEP_URL}
  bcrypt:
    cost: ${BCRYPT_COST}

spring:
  application:
    name: ${APP_NAME}
  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
       client:
         config:
           ViaCepClient:
             connect-timeout: ${VIA_CEP_CONNECT_TIMEOUT}
             read-timeout: ${VIA_CEP_READ_TIMEOUT}
    function:
      definition:
        insertContractEvent;
        installmentPaymentEvent
    stream:
      bindings:
        insertContractEvent-in-0:
          destination: finsys-insert-contract
          group: finsys-events-group
        installmentPaymentEvent-in-0:
          destination: finsys-installment-payment
          group: finsys-events-group
  data:
    mongodb:
      uri: ${MONGO_URI}

resilience4j:
  retry:
    configs:
      default:
        max-attempts: ${DEFAULT_MAX_ATTEMPTS}
        wait-duration: ${DEFAULT_WAIT_DURATION}
    instances:
      viaCepRetry:
          max-attempts: ${VIA_CEP_MAX_ATTEMPTS}
          wait-duration: ${VIA_CEP_WAIT_DURATION}